spring:
  application:
    name: itoken-web-admin
  zipkin:
    base-url: http://localhost:9411
  boot:
    admin:
      client:
        url: http://localhost:8084
  thymeleaf:
    servlet:
      content-type: text/html
    cache: false
    mode: LEGACYHTML5
    encoding: UTF-8
server:
  port: 8601
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info
feign:
  hystrix:
    enabled: true
